apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: mongoadmin
  MONGO_INITDB_ROOT_PASSWORD: mongopass
  MONGO_URI: mongodb://mongoadmin:mongopass@mongo-service:27017/?authSource=admin
  MONGO_DB: cloud_practice_files
  MONGO_COLLECTION: work_documents
